update with 5.8 (#1)
* Remove changes accidentally made on master branch

* Add magic method __call to add query scopes on the fly

* Formatting

* Set the defaults (name, email) on the contact page for logged in users.

* Revert "Set the defaults (name, email) on the contact page for logged in users."

This reverts commit ec807ec52686c88e6625c930301154a2d6fe86f9.

* Set the defaults (name, email) on the contact page for logged in users.

* Use a new `fa-trash` fontawesome 5 icon.

* `btn-default` -> `btn-primary`.

* `fa-refresh` -> `fa-sync`.

* - Update to laravel commit: c9e612f51026ecdeb0f5b13e9d8f4322dceefec7

* Apply fixes from StyleCI

* - Right in view

* Apply fixes from StyleCI

* - Fix geoip crash

* Changed example file location

Makes the test pass

* - [ ] Convert all validation to array syntax

* Apply fixes from StyleCI

* - [ ] Upgrade to laravel commit: c09519f547ae7a97eb26433f159cd81b8753e666

* Apply fixes from StyleCI

* add ukrainian language

* change config.locale uk lang order

* - Update to laravel commit: d1db3cd089d6e9f81a4c8a65d401939f85cbbd5c

* Apply fixes from StyleCI

* - Composer update

* - Composer update

* Test

* Spanish (ES) translation improvements/corrections

* Spanish (ES) translation improvements/corrections

* - Composer update

- Yarn upgrade

* - Set password changed at timestamp when resetting password.

* Apply fixes from StyleCI

* - Add package lock

* - WIP

* - Composer update

* Removed config helper from route and moved condition to actions

* Added `.default` to Vue component requires 

JeffreyWay mentioned this in the "Breaking" section here: https://github.com/JeffreyWay/laravel-mix/releases/tag/v4.0.0
with a matching commit here: https://github.com/laravel/laravel/commit/dc58f95ebbf15b8902ccaef4e2aaa6b0ecbb0e96
to finally a PR here: https://github.com/laravel/laravel/pull/4882/commits/dc58f95ebbf15b8902ccaef4e2aaa6b0ecbb0e96#diff-b7c96b83e41797041ea5067055f8b2af

Without this change upon a new clone you would get a `[Vue warn]: Failed to mount component: template or render function not defined.` error in the console.

* Switch from "env" to "@babel/preset-env"

This will DESTROY `Error: Cannot find module 'babel-preset-env'`

* Compile Assets using new `.babelrc`

* Compiled using production script

* - Update

* - Update

* Fixed Duplicate Element Issue in Browser Console

Fixed Issue #1178
Fixed Issue #1183

- Added laravel @method() function to fix it

* - Update

* - Composer update

* - Update to laravel commit: 2a1f3761e89df690190e9f50a6b4ac5ebb8b35a3

* Apply fixes from StyleCI

* - WIP

* - WIP

* setting resource root

as seen on: https://www.samundra.com.np/integrating-font-awesome-with-laravel-5.x-using-webpack/1574

* - Update template

* Sweetalert2 JS dependancy update

* Sweetalert2 JS Library update code changes

* Sweetalert2 JS library update code changes

* Fix issue with HTML not being rendered in message
issue #1195

* - Upgrade to Laravel 5.8

- [ ] Upgrade to Laravel 5.8
- [ ] Upgrade to phpunit 8.0
- [ ] Upgrade to phpunit-results-printer 0.26.1
- [ ] Update to Laravel commit: 4997f08105d6fb941b1ed2c749ebd2f55fba5a74
- [ ] Remove BladeServiceProvider and register in the boot method of AppServiceProvider as per 5.8 docs
- [ ] Use assertStringContainsString instead of assertContains to make all current tests pass
- [ ] Laravel 5.8 uses bigIncrements as default for the users table so the foreign keys had to be converted to bigIntegers

* Apply fixes from StyleCI

* - [ ] Remove webpatser/laravel-uuid and convert UUID functions to Laravel 5.8’s built in UUID package from Ramsey

* - Update log viewer and nocaptcha

* Apply fixes from StyleCI

* - Upgrade all dev packages

* - Remove CircleCI badge

* - Assets

* - Yarn upgrade

* - Make GA use env

* Apply fixes from StyleCI

* - Escape outputs

* - Think this ones ok

* - Fix count method

* - Fix outputs

* - Update password validation rule

* - Updates

- [ ] Remove withInput parameter in GeneralException since it is covered by the dontReport property of the parent class
- [ ] Don’t report GeneralException errors
- [ ] Add new ReportableException class to throw when you want it to be logged, one of the two can be extended to add new exceptions that you either do or do not want logged. Both still redirect with the flash message.

* Apply fixes from StyleCI

* - Change captcha packages and add captcha to contact

* Apply fixes from StyleCI

* - [ ] Updated single login to use features with AuthenticateMiddleware to work with every driver as well as logout users on other devices

* Apply fixes from StyleCI

* - Update to Laravel: 3886012c0f3ad5653d9d5138530f3fc4276eaf93

* - Add base auditable package

* Apply fixes from StyleCI

* - Include redis

- Change Clear Session button to be driver agnostic, sets a flag that triggers part of the web middleware to force the user to log out

* Apply fixes from StyleCI

* - Add test

* Apply fixes from StyleCI

* - Remove boilerplate html from CoreUI

* - Add missing

* Apply fixes from StyleCI

* - [ ] Fix: Socially logged in users get assigned the default role

* - Load helpers with service provider instead of composer

* Apply fixes from StyleCI

* - Cleanup

* Apply fixes from StyleCI

* - Utilize cast properties

* Apply fixes from StyleCI

* - Update

* - Update migrations

* Added composer self-diagnosis, which passes

* - Upgrade npm scripts

* - Move to dev

* - Update

* - Try to get circle ci to pass

* - WIP

* - Fix logic that fixes tests

* - Add test

* Apply fixes from StyleCI

* updated composer.lock

* updated with babel-template

* feat: making scripts work for both npm and yarn users

* Enforce Unix newlines

* - WIP

* - WIP

* - WIP

* fix: tests with jest

* refactor: mix configuration

Changed fontawesome svg for fontawesome web to improve compatibilite with old browsers and improve resources weight

* - Flair

* - Fix yarn tests

* - Update

* - Test

* - Test

* - Test

* feat: Using PHP-CS-Fixer the right way

* refactor: removed unneeded simple-line-icons

* chore: updated package-lock.json

* - Compile

* - Run CS Fixer

* Update labels.php

remove duplicate array key

* Complete Dutch translations

* change double quotes

* - Update

* - Added shouldDiscoverEvents but default to false

* - Upgrade to laravel commit: 3995828c13ddca61dec45b8f9511a669cc90a15c

* - Reset since i don’t have a paid account

* Apply fixes from StyleCI

* - Add missing tooltip call

* - Fix session encrypt

* - [ ] Default send confirmation email on new users to off since confirmed is defaulted to on

* - Move log viewer links under isAdmin

* - [ ] Execute SubstituteBindings after LocaleMiddleware

* - Fixed google analytics code

* - Remove redis as default

* - Added demo mode

* Apply fixes from StyleCI

* - Add demo creds

* - upgrade jQuery, A prototype pollution vulnerability exists in jQuery versions < 3.4.0 that allows an attacker to inject properties on Object.prototype.

* - Assets

* - Change to mailhog default

* - Update to laravel commit ebc6f6e2c794b07c6d432483fd654aebf2ffe222

* - Undo

* Apply fixes from StyleCI

* - package.json updates